
FROM prefecthq/prefect:3.0.0rc14-python3.11

USER root

WORKDIR /app

COPY make/requirements.txt /tmp/requirements.txt

RUN apt-get update && \
    apt-get install -y curl git && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    pip install --upgrade streamlit && \
    rm -rf /var/lib/apt/lists/* \
COPY streamlit /app

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]